# Site wide configuration
title: meo modo
description: operandi
locale: en_US
logo: assets/images/logo.png
url: https://bradford.la

# Global Variables
img-dir-posts: assets/images/posts
img-dir-posts-arch: assets/images/archive

# Jekyll configuration
permalink: /blog/:year/title.html
markdown:    kramdown
highlighter: rouge
paginate: 5
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap
  - jekyll-gist
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  enable_coderay: false

mathjax: true

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]

# Default extensions
post_ext: md
page_ext: md

# Found in _templates/
post_layout: post
page_layout: page

# Format titles with titlecase?
titlecase: true

# Site owner
owner:
  name: Bradford
  avatar: "https://avatars3.githubusercontent.com/u/1217269?v=3&s=190"
  email:
  disqus-shortname: meomodo
  twitter: meomod
  facebook: #username
  github: elBradford
  stackoverflow: 1486966
  linkedin: bradfordl
  instagram: #username
  flickr: #username
  tumblr: #username
  pinterest: #username
  weibo: #userid
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify: DFE7FC91A392FC461246F68D60BA1324

# Front Page Variables
# about 5 elements are recomended
front_page_name: Bradford
github_username:  elBradford
twitter_username: meomod
linkedin_username: bradfordl
stack_of_username: 1486966
blog_url: "/posts"
public_key_url: "https://raw.pastebin.com/LINK-TO-PUBLIC-KEY"
avatar: yes
#avatar_img_path: "imgs/avatar.jpg""
# You can link to your GitHub image. That way it will get updated
# automatically whenever you change your GitHub profile picture
avatar_img_path: "https://avatars3.githubusercontent.com/u/1217269?v=3&s=190"
front_img: yes
front_img_path: "assets/images/background.jpg"
#front_img_path: "https://external.url/image.jpg"
